# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160903_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(hello.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
